##############################################################################
## This file is part of 'Example Firmware'.
## It is subject to the license terms in the LICENSE.txt file found in the 
## top-level directory of this distribution and at: 
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html. 
## No part of 'Example Firmware', including this file, 
## may be copied, modified, propagated, or distributed except according to 
## the terms contained in the LICENSE.txt file.
##############################################################################

<<<<<<< HEAD:firmware/targets/LsstIonPumpCtrl/vivado/promgen.tcl
# SPI PROM
set format     "mcs"
set inteface   "spix1"
set size       "256"
=======
set_property LOC U1    [get_ports dacSclk[5]]
set_property LOC B2    [get_ports dacSclk[4]]
set_property LOC A16   [get_ports dacSclk[3]]
set_property LOC AB7   [get_ports dacSclk[2]]
set_property LOC AA15  [get_ports dacSclk[1]]
set_property LOC G22   [get_ports dacSclk[0]]
set_property LOC R2    [get_ports adcSclk[5]]
set_property LOC D1    [get_ports adcSclk[4]]
set_property LOC B17   [get_ports adcSclk[3]]
set_property LOC AA6   [get_ports adcSclk[2]]
set_property LOC AA14  [get_ports adcSclk[1]]
set_property LOC H22   [get_ports adcSclk[0]]
set_property LOC AB21  [get_ports ResetN]
set_property LOC V17   [get_ports promSda]
set_property LOC AB20  [get_ports promScl]
set_property LOC L12   [get_ports bootSck]
set_property LOC P22   [get_ports bootDout[O]]
set_property LOC R21   [get_ports bootDout[3]]
set_property LOC P21   [get_ports bootDout[2]]
set_property LOC R22   [get_ports bootDout[1]]
set_property LOC T19   [get_ports bootDout]
set_property LOC F10   [get_ports mgtClkP]
set_property LOC E10   [get_ports mgtClkN]
set_property LOC T1    [get_ports vProgCsN[5]]
set_property LOC B1    [get_ports vProgCsN[4]]
set_property LOC B15   [get_ports vProgCsN[3]]
set_property LOC AA8   [get_ports vProgCsN[2]]
set_property LOC AB16  [get_ports vProgCsN[1]]
set_property LOC F21   [get_ports vProgCsN[0]]
set_property LOC N2    [get_ports vMonDin[5]]
set_property LOC F1    [get_ports vMonDin[4]]
set_property LOC A20   [get_ports vMonDin[3]]
set_property LOC AB3   [get_ports vMonDin[2]]
set_property LOC AB11  [get_ports vMonDin[1]]
set_property LOC K22   [get_ports vMonDin[0]]
set_property LOC M2    [get_ports vMode[5]]
set_property LOC E2    [get_ports vMode[4]]
set_property LOC A19   [get_ports vMode[3]]
set_property LOC AA4   [get_ports vMode[2]]
set_property LOC AB12  [get_ports vMode[1]]
set_property LOC K21   [get_ports vMode[0]]
set_property LOC B4    [get_ports txP]
set_property LOC A4    [get_ports txM]
set_property LOC B8    [get_ports rxP]
set_property LOC A8    [get_ports rxM]
set_property LOC R1    [get_ports pProgCsN[5]]
set_property LOC C2    [get_ports pProgCsN[4]]
set_property LOC B16   [get_ports pProgCsN[3]]
set_property LOC AB6   [get_ports pProgCsN[2]]
set_property LOC AB15  [get_ports pProgCsN[1]]
set_property LOC G21   [get_ports pProgCsN[0]]
set_property LOC M1    [get_ports pMonDin[5]]
set_property LOC G2    [get_ports pMonDin[4]]
set_property LOC A21   [get_ports pMonDin[3]]
set_property LOC AB2   [get_ports pMonDin[2]]
set_property LOC AB10  [get_ports pMonDin[1]]
set_property LOC M22   [get_ports pMonDin[0]]
set_property LOC L1    [get_ports pMode[5]]
set_property LOC G1    [get_ports pMode[4]]
set_property LOC B20   [get_ports pMode[3]]
set_property LOC AA3   [get_ports pMode[2]]
set_property LOC AA11  [get_ports pMode[1]]
set_property LOC L21   [get_ports pMode[0]]
set_property LOC U2    [get_ports iProgCsN[5]]
set_property LOC A1    [get_ports iProgCsN[4]]
set_property LOC A15   [get_ports iProgCsN[3]]
set_property LOC AB8   [get_ports iProgCsN[2]]
set_property LOC AA16  [get_ports iProgCsN[1]]
set_property LOC E22   [get_ports iProgCsN[0]]
set_property LOC P1    [get_ports iMonDin[5]]
set_property LOC E1    [get_ports iMonDin[4]]
set_property LOC B18   [get_ports iMonDin[3]]
set_property LOC AA5   [get_ports iMonDin[2]]
set_property LOC AA13  [get_ports iMonDin[1]]
set_property LOC J22   [get_ports iMonDin[0]]
set_property LOC P2    [get_ports iMode[5]]
set_property LOC D2    [get_ports iMode[4]]
set_property LOC A18   [get_ports iMode[3]]
set_property LOC AB5   [get_ports iMode[2]]
set_property LOC AB13  [get_ports iMode[1]]
set_property LOC J21   [get_ports iMode[0]]
set_property LOC K1    [get_ports enable[5]]
set_property LOC H2    [get_ports enable[4]]
set_property LOC B21   [get_ports enable[3]]
set_property LOC AB1   [get_ports enable[2]]
set_property LOC AA10  [get_ports enable[1]]
set_property LOC M21   [get_ports enable[0]]
set_property LOC K2    [get_ports dacOut[5]]
set_property LOC J1    [get_ports dacOut[4]]
set_property LOC B22   [get_ports dacOut[3]]
set_property LOC AA1   [get_ports dacOut[2]]
set_property LOC AA9   [get_ports dacOut[1]]
set_property LOC N22   [get_ports dacOut[0]]

####################################
## Application Timing Constraints ##
####################################
>>>>>>> Progress Save:firmware/targets/lsst-ion-pump-ps-controller/hdl/lsst-ion-pump-ps-contoller.xdc

